2023-04-28 13:20:04,236	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2023-04-28 13:20:04,248	Job number is not available yet
2023-04-28 13:20:04,253	Job number is not available yet
2023-04-28 13:20:04,277	File already exists: /var/loadtest/logs/2023-04-28_13-20-03.889592/phantom_stat_tYBPW3.log
2023-04-28 13:20:04,282	File already exists: /var/loadtest/logs/2023-04-28_13-20-03.889592/phout_BZkbKw.log
2023-04-28 13:20:04,288	File already exists: /var/loadtest/logs/2023-04-28_13-20-03.889592/answ_A2hPO_.log
2023-04-28 13:20:04,294	File not found to collect: validation_error.yaml
2023-04-28 13:20:04,299	File already exists: /var/loadtest/logs/2023-04-28_13-20-03.889592/phantom_ht_u5a.log
2023-04-28 13:23:58,054	Failed to read Overload API token from token.txt
2023-04-28 13:23:58,063	Exception occurred:
<type 'exceptions.RuntimeError'>: API token error
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 377, in run
    self.core.plugins_prepare_test()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 254, in plugins_prepare_test
    plugin.prepare_test()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 239, in prepare_test
    lp_job = self.lp_job

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 553, in lp_job
    self._lp_job = self.__get_lp_job()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 569, in __get_lp_job
    api_client = self.__get_api_client()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 529, in __get_api_client
    self._api_token = self.read_token(self.get_option("token_file"))

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 631, in read_token
    raise RuntimeError("API token error")

2023-04-28 13:23:58,088	Job number is not available yet
2023-04-28 13:23:58,090	Job number is not available yet
2023-04-28 13:23:58,113	File already exists: /var/loadtest/logs/2023-04-28_13-23-56.009343/phantom_stat_zkIWS0.log
2023-04-28 13:23:58,117	File already exists: /var/loadtest/logs/2023-04-28_13-23-56.009343/phantom_u77Rp7.log
2023-04-28 13:23:58,122	File already exists: /var/loadtest/logs/2023-04-28_13-23-56.009343/phout_lCuGqK.log
2023-04-28 13:23:58,128	File already exists: /var/loadtest/logs/2023-04-28_13-23-56.009343/phantom_yJf0_Y.conf
2023-04-28 13:23:58,132	File not found to collect: validation_error.yaml
2023-04-28 13:23:58,138	File already exists: /var/loadtest/logs/2023-04-28_13-23-56.009343/answ_YdxZcv.log
2023-04-28 13:25:39,301	File already exists: /var/loadtest/logs/2023-04-28_13-25-08.368263/phantom_0GQMYC.log
2023-04-28 13:25:39,308	File already exists: /var/loadtest/logs/2023-04-28_13-25-08.368263/phantom_stdout_stderr_WRzngm.log
2023-04-28 13:25:39,314	File already exists: /var/loadtest/logs/2023-04-28_13-25-08.368263/phantom_stat_xDBBlV.log
2023-04-28 13:25:39,318	File already exists: /var/loadtest/logs/2023-04-28_13-25-08.368263/answ_NdI2XR.log
2023-04-28 13:25:39,324	File not found to collect: validation_error.yaml
2023-04-28 13:25:39,331	File already exists: /var/loadtest/logs/2023-04-28_13-25-08.368263/phout_3PuCkw.log
2023-04-28 13:25:39,347	File already exists: /var/loadtest/logs/2023-04-28_13-25-08.368263/phantom_JV0vw_.conf
2023-04-28 13:49:30,568	Exception occurred:
<type 'exceptions.RuntimeError'>: Neither ammofile nor uris specified
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 106, in config_file
    self._config_file = self.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 114, in compose_config
    streams_config += stream.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 288, in compose_config
    self.stepper_wrapper.prepare_stepper()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 212, in prepare_stepper
    self.stpd = self.__get_stpd_filename()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 266, in __get_stpd_filename
    raise RuntimeError("Neither ammofile nor uris specified")

2023-04-28 13:49:30,580	Job number is not available yet
2023-04-28 13:49:30,583	Job number is not available yet
2023-04-28 13:49:30,623	File already exists: /var/loadtest/logs/2023-04-28_13-49-30.225708/phantom_wIx9A_.log
2023-04-28 13:49:30,628	File already exists: /var/loadtest/logs/2023-04-28_13-49-30.225708/answ_O1nBL_.log
2023-04-28 13:49:30,633	File not found to collect: validation_error.yaml
2023-04-28 13:49:30,638	File already exists: /var/loadtest/logs/2023-04-28_13-49-30.225708/phout_ieQjOh.log
2023-04-28 13:49:30,643	File already exists: /var/loadtest/logs/2023-04-28_13-49-30.225708/phantom_stat_D8wWXp.log
2023-04-28 13:50:38,251	Exception occurred:
<class 'yandextank.stepper.module_exceptions.AmmoFileError'>: Error while reading ammo file. Position: 47, header: '/user/register?first_name=test&second_name=test', original exception: invalid literal for int() with base 10: '/user/register?first_name=test&second_name=test'
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 106, in config_file
    self._config_file = self.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 114, in compose_config
    streams_config += stream.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 288, in compose_config
    self.stepper_wrapper.prepare_stepper()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 228, in prepare_stepper
    self.__make_stpd_file()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 318, in __make_stpd_file
    stepper.write(os)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 61, in write
    for missile in self.ammo:

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/format.py", line 19, in <genexpr>
    "%s %s %s\n%s\n" % (len(missile), timestamp, marker, missile)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 48, in <genexpr>
    return ((timestamp, marker or self.marker(missile), missile)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 43, in <genexpr>
    ammo

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 44, in <genexpr>
    for ammo in ((missile, marker or self.marker(missile))

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/missile.py", line 358, in __iter__
    % (ammo_file.tell(), chunk_header, e))

2023-04-28 13:50:38,265	Job number is not available yet
2023-04-28 13:50:38,268	Job number is not available yet
2023-04-28 13:50:38,298	File already exists: /var/loadtest/logs/2023-04-28_13-50-37.849340/answ_lScxpW.log
2023-04-28 13:50:38,303	File already exists: /var/loadtest/logs/2023-04-28_13-50-37.849340/phantom_zrov75.log
2023-04-28 13:50:38,309	File not found to collect: validation_error.yaml
2023-04-28 13:50:38,315	File already exists: /var/loadtest/logs/2023-04-28_13-50-37.849340/phout_BVqDdZ.log
2023-04-28 13:50:38,319	File already exists: /var/loadtest/logs/2023-04-28_13-50-37.849340/phantom_stat_NY7bsB.log
2023-04-28 13:56:16,374	File not found to collect: validation_error.yaml
2023-04-28 13:56:16,381	File already exists: /var/loadtest/logs/2023-04-28_13-55-32.356556/phantom_zFF2Oh.conf
2023-04-28 13:56:16,387	File already exists: /var/loadtest/logs/2023-04-28_13-55-32.356556/phantom_stat_9Ra7eO.log
2023-04-28 13:56:16,393	File already exists: /var/loadtest/logs/2023-04-28_13-55-32.356556/phout_DRvIEm.log
2023-04-28 13:56:16,412	File already exists: /var/loadtest/logs/2023-04-28_13-55-32.356556/phantom_o8p2uL.log
2023-04-28 13:56:16,416	File already exists: /var/loadtest/logs/2023-04-28_13-55-32.356556/phantom_stdout_stderr_BBaFEI.log
2023-04-28 13:56:16,420	File already exists: /var/loadtest/logs/2023-04-28_13-55-32.356556/answ_h_OBGM.log
2023-04-28 13:58:10,710	Sparkline got outdated second 1682690244, oldest in list 1682690246
2023-04-28 13:58:10,722	Sparkline got outdated second 1682690244, oldest in list 1682690246
2023-04-28 13:58:10,726	Sparkline got outdated second 1682690244, oldest in list 1682690246
2023-04-28 13:58:10,729	Sparkline got outdated second 1682690244, oldest in list 1682690246
2023-04-28 13:58:10,732	Sparkline got outdated second 1682690244, oldest in list 1682690246
2023-04-28 13:58:10,736	Sparkline got outdated second 1682690244, oldest in list 1682690246
2023-04-28 13:58:10,741	Sparkline got outdated second 1682690244, oldest in list 1682690246
2023-04-28 13:58:10,745	Sparkline got outdated second 1682690244, oldest in list 1682690246
2023-04-28 13:58:10,750	Sparkline got outdated second 1682690244, oldest in list 1682690246
2023-04-28 13:58:10,767	Sparkline got outdated second 1682690245, oldest in list 1682690246
2023-04-28 13:58:10,778	Sparkline got outdated second 1682690245, oldest in list 1682690246
2023-04-28 13:58:10,782	Sparkline got outdated second 1682690245, oldest in list 1682690246
2023-04-28 13:58:10,786	Sparkline got outdated second 1682690245, oldest in list 1682690246
2023-04-28 13:58:10,790	Sparkline got outdated second 1682690245, oldest in list 1682690246
2023-04-28 13:58:10,793	Sparkline got outdated second 1682690245, oldest in list 1682690246
2023-04-28 13:58:10,796	Sparkline got outdated second 1682690245, oldest in list 1682690246
2023-04-28 13:58:10,799	Sparkline got outdated second 1682690245, oldest in list 1682690246
2023-04-28 13:58:10,803	Sparkline got outdated second 1682690245, oldest in list 1682690246
2023-04-28 13:58:12,340	File already exists: /var/loadtest/logs/2023-04-28_13-57-20.688585/answ_PGRnrA.log
2023-04-28 13:58:12,346	File already exists: /var/loadtest/logs/2023-04-28_13-57-20.688585/phout_tBdPYl.log
2023-04-28 13:58:12,356	File already exists: /var/loadtest/logs/2023-04-28_13-57-20.688585/phantom_stat_KUCObg.log
2023-04-28 13:58:12,365	File not found to collect: validation_error.yaml
2023-04-28 13:58:12,386	File already exists: /var/loadtest/logs/2023-04-28_13-57-20.688585/phantom_stdout_stderr_Pti0Wm.log
2023-04-28 13:58:12,395	File already exists: /var/loadtest/logs/2023-04-28_13-57-20.688585/phantom_Wm3M2d.log
2023-04-28 13:58:12,400	File already exists: /var/loadtest/logs/2023-04-28_13-57-20.688585/phantom_gndAQC.conf
2023-04-28 14:00:13,255	File already exists: /var/loadtest/logs/2023-04-28_13-59-31.588309/phout_kA0tBG.log
2023-04-28 14:00:13,261	File already exists: /var/loadtest/logs/2023-04-28_13-59-31.588309/answ_rBk6P2.log
2023-04-28 14:00:13,267	File already exists: /var/loadtest/logs/2023-04-28_13-59-31.588309/phantom_DLG0fK.log
2023-04-28 14:00:13,271	File already exists: /var/loadtest/logs/2023-04-28_13-59-31.588309/phantom_y3_jK8.conf
2023-04-28 14:00:13,278	File not found to collect: validation_error.yaml
2023-04-28 14:00:13,293	File already exists: /var/loadtest/logs/2023-04-28_13-59-31.588309/phantom_stdout_stderr_vCnT7k.log
2023-04-28 14:00:13,298	File already exists: /var/loadtest/logs/2023-04-28_13-59-31.588309/phantom_stat_ZVDtRG.log
2023-04-28 14:04:11,354	File already exists: /var/loadtest/logs/2023-04-28_14-03-16.177696/answ_kGHcua.log
2023-04-28 14:04:11,360	File already exists: /var/loadtest/logs/2023-04-28_14-03-16.177696/phout_E0MS7q.log
2023-04-28 14:04:11,365	File already exists: /var/loadtest/logs/2023-04-28_14-03-16.177696/phantom_oYUFsd.log
2023-04-28 14:04:11,369	File already exists: /var/loadtest/logs/2023-04-28_14-03-16.177696/phantom_R9n6Kx.conf
2023-04-28 14:04:11,374	File already exists: /var/loadtest/logs/2023-04-28_14-03-16.177696/phantom_stdout_stderr_JlvlWo.log
2023-04-28 14:04:11,380	File not found to collect: validation_error.yaml
2023-04-28 14:04:11,384	File already exists: /var/loadtest/logs/2023-04-28_14-03-16.177696/phantom_stat_Ir6x8A.log
2023-04-28 14:12:13,519	Autostop criterion requested test stop: http(5xx,20%,1)
2023-04-28 14:12:13,610	Autostop criterion requested test stop: 5xx codes count higher than 20.0% for 1s, since 1682691129
2023-04-28 14:12:16,610	Failed post-processing plugin <yandextank.plugins.DataUploader.plugin.Plugin object at 0x4019299e90>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 336, in plugins_post_process
    retcode = plugin.post_process(retcode)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 373, in post_process
    int(rps), autostop.cause_criterion.explain())
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 851, in set_imbalance_and_dsc
    return self.api_client.set_imbalance_and_dsc(self.number, rps, comment)
TypeError: set_imbalance_and_dsc() takes exactly 1 argument (4 given)
2023-04-28 14:12:16,823	File already exists: /var/loadtest/logs/2023-04-28_14-11-41.797879/answ_ef4IQF.log
2023-04-28 14:12:16,834	File already exists: /var/loadtest/logs/2023-04-28_14-11-41.797879/phantom_stat_ovQ6L8.log
2023-04-28 14:12:16,846	File already exists: /var/loadtest/logs/2023-04-28_14-11-41.797879/phantom_Y7EjWN.conf
2023-04-28 14:12:16,856	File already exists: /var/loadtest/logs/2023-04-28_14-11-41.797879/phantom_DGx3mQ.log
2023-04-28 14:12:16,862	File already exists: /var/loadtest/logs/2023-04-28_14-11-41.797879/phantom_stdout_stderr_kpK2JM.log
2023-04-28 14:12:16,871	File not found to collect: validation_error.yaml
2023-04-28 14:12:16,879	File already exists: /var/loadtest/logs/2023-04-28_14-11-41.797879/autostop_report.txt
2023-04-28 14:12:16,901	File already exists: /var/loadtest/logs/2023-04-28_14-11-41.797879/phout_oXCXUB.log
2023-04-28 14:14:28,238	Autostop criterion requested test stop: http(5xx,20%,1)
2023-04-28 14:14:28,343	Autostop criterion requested test stop: 5xx codes count higher than 20.0% for 1s, since 1682691258
2023-04-28 14:14:31,529	Failed post-processing plugin <yandextank.plugins.DataUploader.plugin.Plugin object at 0x4019299e90>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 336, in plugins_post_process
    retcode = plugin.post_process(retcode)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 373, in post_process
    int(rps), autostop.cause_criterion.explain())
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 851, in set_imbalance_and_dsc
    return self.api_client.set_imbalance_and_dsc(self.number, rps, comment)
TypeError: set_imbalance_and_dsc() takes exactly 1 argument (4 given)
2023-04-28 14:14:31,701	File already exists: /var/loadtest/logs/2023-04-28_14-13-55.799186/phantom_jzsQP5.log
2023-04-28 14:14:31,709	File already exists: /var/loadtest/logs/2023-04-28_14-13-55.799186/phout_0x5IqQ.log
2023-04-28 14:14:31,713	File already exists: /var/loadtest/logs/2023-04-28_14-13-55.799186/answ_8OVE01.log
2023-04-28 14:14:31,718	File already exists: /var/loadtest/logs/2023-04-28_14-13-55.799186/autostop_report.txt
2023-04-28 14:14:31,725	File not found to collect: validation_error.yaml
2023-04-28 14:14:31,731	File already exists: /var/loadtest/logs/2023-04-28_14-13-55.799186/phantom_stat_dUglw5.log
2023-04-28 14:14:31,749	File already exists: /var/loadtest/logs/2023-04-28_14-13-55.799186/phantom_ZHrSXI.conf
2023-04-28 14:14:31,754	File already exists: /var/loadtest/logs/2023-04-28_14-13-55.799186/phantom_stdout_stderr_Q2IvjH.log
2023-04-28 14:15:43,943	Autostop criterion requested test stop: http(5xx,20%,1)
2023-04-28 14:15:43,972	Autostop criterion requested test stop: 5xx codes count higher than 20.0% for 1s, since 1682691339
2023-04-28 14:15:46,638	Failed post-processing plugin <yandextank.plugins.DataUploader.plugin.Plugin object at 0x4019299e90>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 336, in plugins_post_process
    retcode = plugin.post_process(retcode)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 373, in post_process
    int(rps), autostop.cause_criterion.explain())
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 851, in set_imbalance_and_dsc
    return self.api_client.set_imbalance_and_dsc(self.number, rps, comment)
TypeError: set_imbalance_and_dsc() takes exactly 1 argument (4 given)
2023-04-28 14:15:46,850	File already exists: /var/loadtest/logs/2023-04-28_14-15-21.700584/autostop_report.txt
2023-04-28 14:15:46,854	File already exists: /var/loadtest/logs/2023-04-28_14-15-21.700584/answ_DuVuFH.log
2023-04-28 14:15:46,858	File already exists: /var/loadtest/logs/2023-04-28_14-15-21.700584/phantom_stdout_stderr_TYBIJK.log
2023-04-28 14:15:46,863	File already exists: /var/loadtest/logs/2023-04-28_14-15-21.700584/phantom_stat_LPYOEu.log
2023-04-28 14:15:46,867	File already exists: /var/loadtest/logs/2023-04-28_14-15-21.700584/phantom_IsBLI2.conf
2023-04-28 14:15:46,873	File not found to collect: validation_error.yaml
2023-04-28 14:15:46,889	File already exists: /var/loadtest/logs/2023-04-28_14-15-21.700584/phout_a_cpHt.log
2023-04-28 14:15:46,894	File already exists: /var/loadtest/logs/2023-04-28_14-15-21.700584/phantom_RwCO3T.log
2023-04-28 14:16:34,493	File already exists: /var/loadtest/logs/2023-04-28_14-16-13.727498/phout__qCg12.log
2023-04-28 14:16:34,499	File already exists: /var/loadtest/logs/2023-04-28_14-16-13.727498/phantom_stdout_stderr_LhEVhv.log
2023-04-28 14:16:34,504	File already exists: /var/loadtest/logs/2023-04-28_14-16-13.727498/answ_Y9vrYT.log
2023-04-28 14:16:34,509	File not found to collect: validation_error.yaml
2023-04-28 14:16:34,513	File already exists: /var/loadtest/logs/2023-04-28_14-16-13.727498/phantom_stat_d0KOkf.log
2023-04-28 14:16:34,530	File already exists: /var/loadtest/logs/2023-04-28_14-16-13.727498/phantom_CTlBbH.log
2023-04-28 14:16:34,534	File already exists: /var/loadtest/logs/2023-04-28_14-16-13.727498/phantom_4_krc2.conf
2023-04-28 15:16:20,390	Autostop criterion requested test stop: http(5xx,20%,1)
2023-04-28 15:16:20,425	Autostop criterion requested test stop: 5xx codes count higher than 20.0% for 1s, since 1682694976
2023-04-28 15:16:23,920	Failed post-processing plugin <yandextank.plugins.DataUploader.plugin.Plugin object at 0x4019299e90>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 336, in plugins_post_process
    retcode = plugin.post_process(retcode)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 373, in post_process
    int(rps), autostop.cause_criterion.explain())
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 851, in set_imbalance_and_dsc
    return self.api_client.set_imbalance_and_dsc(self.number, rps, comment)
TypeError: set_imbalance_and_dsc() takes exactly 1 argument (4 given)
2023-04-28 15:16:24,118	File already exists: /var/loadtest/logs/2023-04-28_15-16-02.462756/autostop_report.txt
2023-04-28 15:16:24,123	File already exists: /var/loadtest/logs/2023-04-28_15-16-02.462756/phantom_stat_h2EIt1.log
2023-04-28 15:16:24,128	File already exists: /var/loadtest/logs/2023-04-28_15-16-02.462756/phout_5GJDUY.log
2023-04-28 15:16:24,133	File already exists: /var/loadtest/logs/2023-04-28_15-16-02.462756/phantom_s6g6Dj.conf
2023-04-28 15:16:24,139	File not found to collect: validation_error.yaml
2023-04-28 15:16:24,145	File already exists: /var/loadtest/logs/2023-04-28_15-16-02.462756/phantom_4tBQeG.log
2023-04-28 15:16:24,161	File already exists: /var/loadtest/logs/2023-04-28_15-16-02.462756/phantom_stdout_stderr_AvI30I.log
2023-04-28 15:16:24,165	File already exists: /var/loadtest/logs/2023-04-28_15-16-02.462756/answ_OrDm2L.log
2023-04-28 15:18:33,576	File already exists: /var/loadtest/logs/2023-04-28_15-18-12.199103/phantom_4kVqnU.log
2023-04-28 15:18:33,580	File already exists: /var/loadtest/logs/2023-04-28_15-18-12.199103/phantom_AO7aMm.conf
2023-04-28 15:18:33,585	File already exists: /var/loadtest/logs/2023-04-28_15-18-12.199103/answ_MEGOwE.log
2023-04-28 15:18:33,591	File not found to collect: validation_error.yaml
2023-04-28 15:18:33,606	File already exists: /var/loadtest/logs/2023-04-28_15-18-12.199103/phout_XVtNPR.log
2023-04-28 15:18:33,610	File already exists: /var/loadtest/logs/2023-04-28_15-18-12.199103/phantom_stdout_stderr_dVf7oU.log
2023-04-28 15:18:33,616	File already exists: /var/loadtest/logs/2023-04-28_15-18-12.199103/phantom_stat_UvwODB.log
2023-04-28 15:20:11,950	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2023-04-28 15:20:11,972	Job number is not available yet
2023-04-28 15:20:11,977	Job number is not available yet
2023-04-28 15:20:12,004	File already exists: /var/loadtest/logs/2023-04-28_15-19-56.496730/phantom_6Bumlb.log
2023-04-28 15:20:12,008	File already exists: /var/loadtest/logs/2023-04-28_15-19-56.496730/phout_gFRRyj.log
2023-04-28 15:20:12,013	File already exists: /var/loadtest/logs/2023-04-28_15-19-56.496730/answ_NqXy6t.log
2023-04-28 15:20:12,020	File not found to collect: validation_error.yaml
2023-04-28 15:20:12,024	File already exists: /var/loadtest/logs/2023-04-28_15-19-56.496730/phantom_stat_7dbVTE.log
2023-04-28 15:22:02,917	Interrupting
2023-04-28 15:22:06,434	File already exists: /var/loadtest/logs/2023-04-28_15-20-50.462008/phantom_stat_jChwWf.log
2023-04-28 15:22:06,440	File already exists: /var/loadtest/logs/2023-04-28_15-20-50.462008/phantom_stdout_stderr_Tt0nJc.log
2023-04-28 15:22:06,447	File already exists: /var/loadtest/logs/2023-04-28_15-20-50.462008/phantom_GXP12f.log
2023-04-28 15:22:06,452	File already exists: /var/loadtest/logs/2023-04-28_15-20-50.462008/phantom_eHxxjD.conf
2023-04-28 15:22:06,458	File not found to collect: validation_error.yaml
2023-04-28 15:22:06,462	File already exists: /var/loadtest/logs/2023-04-28_15-20-50.462008/answ_BjBXbS.log
2023-04-28 15:22:06,477	File already exists: /var/loadtest/logs/2023-04-28_15-20-50.462008/phout_ZiGSYk.log
2023-04-28 15:22:29,247	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2023-04-28 15:22:29,268	Job number is not available yet
2023-04-28 15:22:29,272	Job number is not available yet
2023-04-28 15:22:29,297	File already exists: /var/loadtest/logs/2023-04-28_15-22-13.779070/answ_4LqS0n.log
2023-04-28 15:22:29,301	File already exists: /var/loadtest/logs/2023-04-28_15-22-13.779070/phantom_2fpDoT.log
2023-04-28 15:22:29,307	File not found to collect: validation_error.yaml
2023-04-28 15:22:29,311	File already exists: /var/loadtest/logs/2023-04-28_15-22-13.779070/phantom_stat_fxGc91.log
2023-04-28 15:22:29,316	File already exists: /var/loadtest/logs/2023-04-28_15-22-13.779070/phout_NPff5M.log
2023-04-28 15:24:54,642	Sparkline got outdated second 1682695374, oldest in list 1682695375
2023-04-28 15:24:54,654	Sparkline got outdated second 1682695374, oldest in list 1682695375
2023-04-28 15:24:54,658	Sparkline got outdated second 1682695374, oldest in list 1682695375
2023-04-28 15:24:54,662	Sparkline got outdated second 1682695374, oldest in list 1682695375
2023-04-28 15:24:54,666	Sparkline got outdated second 1682695374, oldest in list 1682695375
2023-04-28 15:24:54,670	Sparkline got outdated second 1682695374, oldest in list 1682695375
2023-04-28 15:24:54,673	Sparkline got outdated second 1682695374, oldest in list 1682695375
2023-04-28 15:24:54,676	Sparkline got outdated second 1682695374, oldest in list 1682695375
2023-04-28 15:24:54,680	Sparkline got outdated second 1682695374, oldest in list 1682695375
2023-04-28 15:24:56,056	File already exists: /var/loadtest/logs/2023-04-28_15-22-50.696016/answ_TrGiT0.log
2023-04-28 15:24:56,060	File already exists: /var/loadtest/logs/2023-04-28_15-22-50.696016/phantom_stdout_stderr_keMS1Z.log
2023-04-28 15:24:56,065	File already exists: /var/loadtest/logs/2023-04-28_15-22-50.696016/phantom_6vT8Ar.log
2023-04-28 15:24:56,073	File already exists: /var/loadtest/logs/2023-04-28_15-22-50.696016/phout_ITN1NP.log
2023-04-28 15:24:56,079	File not found to collect: validation_error.yaml
2023-04-28 15:24:56,094	File already exists: /var/loadtest/logs/2023-04-28_15-22-50.696016/phantom_FkHkOP.conf
2023-04-28 15:24:56,100	File already exists: /var/loadtest/logs/2023-04-28_15-22-50.696016/phantom_stat_HTbwdt.log
2023-04-28 15:28:11,691	Interrupting
2023-04-28 15:28:17,094	File already exists: /var/loadtest/logs/2023-04-28_15-25-47.172093/phantom_cyBTe0.log
2023-04-28 15:28:17,106	File already exists: /var/loadtest/logs/2023-04-28_15-25-47.172093/phantom_stdout_stderr_8k5lXe.log
2023-04-28 15:28:17,111	File already exists: /var/loadtest/logs/2023-04-28_15-25-47.172093/phantom_laltG8.conf
2023-04-28 15:28:17,118	File already exists: /var/loadtest/logs/2023-04-28_15-25-47.172093/phout_2_o8Fz.log
2023-04-28 15:28:17,124	File already exists: /var/loadtest/logs/2023-04-28_15-25-47.172093/answ_EBQIfM.log
2023-04-28 15:28:17,130	File not found to collect: validation_error.yaml
2023-04-28 15:28:17,150	File already exists: /var/loadtest/logs/2023-04-28_15-25-47.172093/phantom_stat_mehxvU.log
2023-04-29 20:51:02,872	Interrupting
2023-04-29 20:51:04,716	Sparkline got outdated second 1682801413, oldest in list 1682801415
2023-04-29 20:51:04,724	Sparkline got outdated second 1682801413, oldest in list 1682801415
2023-04-29 20:51:04,728	Sparkline got outdated second 1682801413, oldest in list 1682801415
2023-04-29 20:51:04,731	Sparkline got outdated second 1682801413, oldest in list 1682801415
2023-04-29 20:51:04,735	Sparkline got outdated second 1682801413, oldest in list 1682801415
2023-04-29 20:51:04,737	Sparkline got outdated second 1682801413, oldest in list 1682801415
2023-04-29 20:51:04,740	Sparkline got outdated second 1682801413, oldest in list 1682801415
2023-04-29 20:51:04,743	Sparkline got outdated second 1682801413, oldest in list 1682801415
2023-04-29 20:51:04,747	Sparkline got outdated second 1682801413, oldest in list 1682801415
2023-04-29 20:51:04,757	Sparkline got outdated second 1682801414, oldest in list 1682801415
2023-04-29 20:51:04,766	Sparkline got outdated second 1682801414, oldest in list 1682801415
2023-04-29 20:51:04,769	Sparkline got outdated second 1682801414, oldest in list 1682801415
2023-04-29 20:51:04,771	Sparkline got outdated second 1682801414, oldest in list 1682801415
2023-04-29 20:51:04,774	Sparkline got outdated second 1682801414, oldest in list 1682801415
2023-04-29 20:51:04,777	Sparkline got outdated second 1682801414, oldest in list 1682801415
2023-04-29 20:51:04,780	Sparkline got outdated second 1682801414, oldest in list 1682801415
2023-04-29 20:51:04,783	Sparkline got outdated second 1682801414, oldest in list 1682801415
2023-04-29 20:51:04,786	Sparkline got outdated second 1682801414, oldest in list 1682801415
2023-04-29 20:51:05,975	File already exists: /var/loadtest/logs/2023-04-29_20-50-09.568353/phout__mBn5J.log
2023-04-29 20:51:05,979	File already exists: /var/loadtest/logs/2023-04-29_20-50-09.568353/phantom_stdout_stderr_DSXWIw.log
2023-04-29 20:51:05,985	File already exists: /var/loadtest/logs/2023-04-29_20-50-09.568353/phantom_stat_v59r3V.log
2023-04-29 20:51:05,991	File not found to collect: validation_error.yaml
2023-04-29 20:51:06,005	File already exists: /var/loadtest/logs/2023-04-29_20-50-09.568353/phantom_uXDc0W.conf
2023-04-29 20:51:06,010	File already exists: /var/loadtest/logs/2023-04-29_20-50-09.568353/phantom_W2OSfN.log
2023-04-29 20:51:06,019	File already exists: /var/loadtest/logs/2023-04-29_20-50-09.568353/answ_RdAdNY.log
2023-04-29 20:51:38,129	Interrupting
2023-04-29 20:51:38,591	Test interrupted:
<type 'exceptions.KeyboardInterrupt'>: 
<traceback object at 0x40192e2d88>
2023-04-29 20:51:41,219	File already exists: /var/loadtest/logs/2023-04-29_20-51-22.788175/phantom_Ikebn7.conf
2023-04-29 20:51:41,223	File already exists: /var/loadtest/logs/2023-04-29_20-51-22.788175/phantom_stdout_stderr_0Pr3Jf.log
2023-04-29 20:51:41,228	File already exists: /var/loadtest/logs/2023-04-29_20-51-22.788175/phantom_NEWGlD.log
2023-04-29 20:51:41,232	File already exists: /var/loadtest/logs/2023-04-29_20-51-22.788175/answ_UnXsbs.log
2023-04-29 20:51:41,239	File not found to collect: validation_error.yaml
2023-04-29 20:51:41,256	File already exists: /var/loadtest/logs/2023-04-29_20-51-22.788175/phantom_stat_SGRNir.log
2023-04-29 20:51:41,263	File already exists: /var/loadtest/logs/2023-04-29_20-51-22.788175/phout_13e_Nc.log
2023-04-29 20:53:46,009	Interrupting
2023-04-29 20:53:48,201	Sparkline got outdated second 1682801593, oldest in list 1682801596
2023-04-29 20:53:48,212	Sparkline got outdated second 1682801593, oldest in list 1682801596
2023-04-29 20:53:48,216	Sparkline got outdated second 1682801593, oldest in list 1682801596
2023-04-29 20:53:48,219	Sparkline got outdated second 1682801593, oldest in list 1682801596
2023-04-29 20:53:48,223	Sparkline got outdated second 1682801593, oldest in list 1682801596
2023-04-29 20:53:48,225	Sparkline got outdated second 1682801593, oldest in list 1682801596
2023-04-29 20:53:48,229	Sparkline got outdated second 1682801593, oldest in list 1682801596
2023-04-29 20:53:48,233	Sparkline got outdated second 1682801593, oldest in list 1682801596
2023-04-29 20:53:48,236	Sparkline got outdated second 1682801593, oldest in list 1682801596
2023-04-29 20:53:48,247	Sparkline got outdated second 1682801594, oldest in list 1682801596
2023-04-29 20:53:48,257	Sparkline got outdated second 1682801594, oldest in list 1682801596
2023-04-29 20:53:48,259	Sparkline got outdated second 1682801594, oldest in list 1682801596
2023-04-29 20:53:48,262	Sparkline got outdated second 1682801594, oldest in list 1682801596
2023-04-29 20:53:48,265	Sparkline got outdated second 1682801594, oldest in list 1682801596
2023-04-29 20:53:48,268	Sparkline got outdated second 1682801594, oldest in list 1682801596
2023-04-29 20:53:48,271	Sparkline got outdated second 1682801594, oldest in list 1682801596
2023-04-29 20:53:48,274	Sparkline got outdated second 1682801594, oldest in list 1682801596
2023-04-29 20:53:48,277	Sparkline got outdated second 1682801594, oldest in list 1682801596
2023-04-29 20:53:48,291	Sparkline got outdated second 1682801595, oldest in list 1682801596
2023-04-29 20:53:48,301	Sparkline got outdated second 1682801595, oldest in list 1682801596
2023-04-29 20:53:48,303	Sparkline got outdated second 1682801595, oldest in list 1682801596
2023-04-29 20:53:48,307	Sparkline got outdated second 1682801595, oldest in list 1682801596
2023-04-29 20:53:48,311	Sparkline got outdated second 1682801595, oldest in list 1682801596
2023-04-29 20:53:48,315	Sparkline got outdated second 1682801595, oldest in list 1682801596
2023-04-29 20:53:48,318	Sparkline got outdated second 1682801595, oldest in list 1682801596
2023-04-29 20:53:48,321	Sparkline got outdated second 1682801595, oldest in list 1682801596
2023-04-29 20:53:48,324	Sparkline got outdated second 1682801595, oldest in list 1682801596
2023-04-29 20:53:49,672	File already exists: /var/loadtest/logs/2023-04-29_20-52-59.539091/phantom_stat_dAlyFM.log
2023-04-29 20:53:49,677	File already exists: /var/loadtest/logs/2023-04-29_20-52-59.539091/phantom_5X4UPI.conf
2023-04-29 20:53:49,683	File already exists: /var/loadtest/logs/2023-04-29_20-52-59.539091/phout_9kIvkp.log
2023-04-29 20:53:49,688	File already exists: /var/loadtest/logs/2023-04-29_20-52-59.539091/phantom_stdout_stderr_G5Kezo.log
2023-04-29 20:53:49,695	File already exists: /var/loadtest/logs/2023-04-29_20-52-59.539091/phantom_rbqkwT.log
2023-04-29 20:53:49,701	File not found to collect: validation_error.yaml
2023-04-29 20:53:49,720	File already exists: /var/loadtest/logs/2023-04-29_20-52-59.539091/answ_VznRKF.log
2023-04-29 20:54:27,802	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2023-04-29 20:54:27,824	Job number is not available yet
2023-04-29 20:54:27,828	Job number is not available yet
2023-04-29 20:54:27,855	File already exists: /var/loadtest/logs/2023-04-29_20-54-12.282849/phout_KW01l1.log
2023-04-29 20:54:27,861	File already exists: /var/loadtest/logs/2023-04-29_20-54-12.282849/phantom_oxOdso.log
2023-04-29 20:54:27,867	File not found to collect: validation_error.yaml
2023-04-29 20:54:27,871	File already exists: /var/loadtest/logs/2023-04-29_20-54-12.282849/answ_dKj7GL.log
2023-04-29 20:54:27,877	File already exists: /var/loadtest/logs/2023-04-29_20-54-12.282849/phantom_stat_aeUQsm.log
2023-04-29 20:55:45,598	Interrupting
2023-04-29 20:55:47,983	Sparkline got outdated second 1682801710, oldest in list 1682801711
2023-04-29 20:55:47,994	Sparkline got outdated second 1682801710, oldest in list 1682801711
2023-04-29 20:55:47,997	Sparkline got outdated second 1682801710, oldest in list 1682801711
2023-04-29 20:55:48,000	Sparkline got outdated second 1682801710, oldest in list 1682801711
2023-04-29 20:55:48,004	Sparkline got outdated second 1682801710, oldest in list 1682801711
2023-04-29 20:55:48,007	Sparkline got outdated second 1682801710, oldest in list 1682801711
2023-04-29 20:55:48,009	Sparkline got outdated second 1682801710, oldest in list 1682801711
2023-04-29 20:55:48,012	Sparkline got outdated second 1682801710, oldest in list 1682801711
2023-04-29 20:55:48,014	Sparkline got outdated second 1682801710, oldest in list 1682801711
2023-04-29 20:55:49,198	File already exists: /var/loadtest/logs/2023-04-29_20-55-04.373813/phantom__tJhbF.conf
2023-04-29 20:55:49,204	File already exists: /var/loadtest/logs/2023-04-29_20-55-04.373813/phantom_stat_eeLOMI.log
2023-04-29 20:55:49,208	File already exists: /var/loadtest/logs/2023-04-29_20-55-04.373813/phantom_stdout_stderr_nWdtlY.log
2023-04-29 20:55:49,213	File not found to collect: validation_error.yaml
2023-04-29 20:55:49,219	File already exists: /var/loadtest/logs/2023-04-29_20-55-04.373813/phout_jmOLet.log
2023-04-29 20:55:49,225	File already exists: /var/loadtest/logs/2023-04-29_20-55-04.373813/phantom_4V1Lhh.log
2023-04-29 20:55:49,230	File already exists: /var/loadtest/logs/2023-04-29_20-55-04.373813/answ_c9ALAV.log
2023-04-29 20:56:57,172	Interrupting
2023-04-29 20:56:59,025	Sparkline got outdated second 1682801794, oldest in list 1682801795
2023-04-29 20:56:59,047	Sparkline got outdated second 1682801794, oldest in list 1682801795
2023-04-29 20:56:59,051	Sparkline got outdated second 1682801794, oldest in list 1682801795
2023-04-29 20:56:59,054	Sparkline got outdated second 1682801794, oldest in list 1682801795
2023-04-29 20:56:59,057	Sparkline got outdated second 1682801794, oldest in list 1682801795
2023-04-29 20:56:59,061	Sparkline got outdated second 1682801794, oldest in list 1682801795
2023-04-29 20:56:59,065	Sparkline got outdated second 1682801794, oldest in list 1682801795
2023-04-29 20:56:59,068	Sparkline got outdated second 1682801794, oldest in list 1682801795
2023-04-29 20:56:59,071	Sparkline got outdated second 1682801794, oldest in list 1682801795
2023-04-29 20:57:00,426	File already exists: /var/loadtest/logs/2023-04-29_20-56-24.458967/phantom_Go0dY8.conf
2023-04-29 20:57:00,430	File already exists: /var/loadtest/logs/2023-04-29_20-56-24.458967/answ_0mu81s.log
2023-04-29 20:57:00,434	File already exists: /var/loadtest/logs/2023-04-29_20-56-24.458967/phantom_stdout_stderr_FXSCSu.log
2023-04-29 20:57:00,441	File already exists: /var/loadtest/logs/2023-04-29_20-56-24.458967/phantom_5Hvw9W.log
2023-04-29 20:57:00,449	File not found to collect: validation_error.yaml
2023-04-29 20:57:00,455	File already exists: /var/loadtest/logs/2023-04-29_20-56-24.458967/phout_VGrRKh.log
2023-04-29 20:57:00,462	File already exists: /var/loadtest/logs/2023-04-29_20-56-24.458967/phantom_stat_8GuPpQ.log
2023-04-29 21:04:13,719	Autostop criterion requested test stop: http(5xx,20%,1)
2023-04-29 21:04:13,755	Autostop criterion requested test stop: 5xx codes count higher than 20.0% for 1s, since 1682802249
2023-04-29 21:04:16,454	Failed post-processing plugin <yandextank.plugins.DataUploader.plugin.Plugin object at 0x40192b5810>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 336, in plugins_post_process
    retcode = plugin.post_process(retcode)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 373, in post_process
    int(rps), autostop.cause_criterion.explain())
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 851, in set_imbalance_and_dsc
    return self.api_client.set_imbalance_and_dsc(self.number, rps, comment)
TypeError: set_imbalance_and_dsc() takes exactly 1 argument (4 given)
2023-04-29 21:04:16,658	File already exists: /var/loadtest/logs/2023-04-29_21-03-58.362228/phantom_stdout_stderr_t1NzMH.log
2023-04-29 21:04:16,663	File already exists: /var/loadtest/logs/2023-04-29_21-03-58.362228/phantom_oiUrdk.log
2023-04-29 21:04:16,669	File already exists: /var/loadtest/logs/2023-04-29_21-03-58.362228/autostop_report.txt
2023-04-29 21:04:16,674	File already exists: /var/loadtest/logs/2023-04-29_21-03-58.362228/phantom_stat_rK6dsR.log
2023-04-29 21:04:16,677	File already exists: /var/loadtest/logs/2023-04-29_21-03-58.362228/answ_nkfY37.log
2023-04-29 21:04:16,681	File already exists: /var/loadtest/logs/2023-04-29_21-03-58.362228/phout_6_B8V3.log
2023-04-29 21:04:16,686	File not found to collect: validation_error.yaml
2023-04-29 21:04:16,701	File already exists: /var/loadtest/logs/2023-04-29_21-03-58.362228/phantom_eEDdeZ.conf
2023-04-29 21:07:04,928	Failed to import _strptime because the import lockis held by another thread.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/netort/data_processing.py", line 36, in run
    for item in self.source:
  File "/usr/local/lib/python2.7/dist-packages/netort/data_processing.py", line 104, in __iter__
    for chunk in self.source:
  File "/usr/local/lib/python2.7/dist-packages/yandextank/aggregator/aggregator.py", line 123, in __iter__
    for chunk in self.source:
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/reader.py", line 162, in __iter__
    yield self._read_stat_data(stat_file)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/reader.py", line 145, in _read_stat_data
    return self._format_chunk(ready_chunk)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/reader.py", line 152, in _format_chunk
    return list(itt.chain(*(self._decode_stat_data(chunk) for chunk in chunks)))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/reader.py", line 121, in _decode_stat_data
    date_str.split(".")[0], '%Y-%m-%d %H:%M:%S')
ImportError: Failed to import _strptime because the import lockis held by another thread.
2023-04-29 21:07:18,544	Autostop criterion requested test stop: http(5xx,20%,1)
2023-04-29 21:07:21,396	Failed post-processing plugin <yandextank.plugins.DataUploader.plugin.Plugin object at 0x40192b5810>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 336, in plugins_post_process
    retcode = plugin.post_process(retcode)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 373, in post_process
    int(rps), autostop.cause_criterion.explain())
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 851, in set_imbalance_and_dsc
    return self.api_client.set_imbalance_and_dsc(self.number, rps, comment)
TypeError: set_imbalance_and_dsc() takes exactly 1 argument (4 given)
2023-04-29 21:07:21,670	File already exists: /var/loadtest/logs/2023-04-29_21-06-58.673061/phantom_4oDWxC.conf
2023-04-29 21:07:21,695	File already exists: /var/loadtest/logs/2023-04-29_21-06-58.673061/phout_MfsX9m.log
2023-04-29 21:07:21,771	File already exists: /var/loadtest/logs/2023-04-29_21-06-58.673061/phantom_XuULjN.log
2023-04-29 21:07:21,820	File already exists: /var/loadtest/logs/2023-04-29_21-06-58.673061/phantom_stat_nFEaOh.log
2023-04-29 21:07:21,848	File already exists: /var/loadtest/logs/2023-04-29_21-06-58.673061/autostop_report.txt
2023-04-29 21:07:21,858	File already exists: /var/loadtest/logs/2023-04-29_21-06-58.673061/phantom_stdout_stderr_JVf3PZ.log
2023-04-29 21:07:21,874	File not found to collect: validation_error.yaml
2023-04-29 21:07:21,908	File already exists: /var/loadtest/logs/2023-04-29_21-06-58.673061/answ_uSM2oe.log
2023-04-29 21:19:48,851	Exception occurred:
<type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode characters in position 34-39: ordinal not in range(128)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 106, in config_file
    self._config_file = self.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 114, in compose_config
    streams_config += stream.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 288, in compose_config
    self.stepper_wrapper.prepare_stepper()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 228, in prepare_stepper
    self.__make_stpd_file()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 318, in __make_stpd_file
    stepper.write(os)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 62, in write
    f.write(missile)

2023-04-29 21:19:48,863	Job number is not available yet
2023-04-29 21:19:48,867	Job number is not available yet
2023-04-29 21:19:48,891	File already exists: /var/loadtest/logs/2023-04-29_21-19-48.456951/phantom_stat_9Tg8fF.log
2023-04-29 21:19:48,895	File already exists: /var/loadtest/logs/2023-04-29_21-19-48.456951/phantom_81FCl9.log
2023-04-29 21:19:48,902	File not found to collect: validation_error.yaml
2023-04-29 21:19:48,907	File already exists: /var/loadtest/logs/2023-04-29_21-19-48.456951/phout_7ke0cK.log
2023-04-29 21:19:48,910	File already exists: /var/loadtest/logs/2023-04-29_21-19-48.456951/answ_UQQeGX.log
2023-04-29 21:20:03,881	Exception occurred:
<type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode characters in position 34-39: ordinal not in range(128)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 106, in config_file
    self._config_file = self.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 114, in compose_config
    streams_config += stream.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 288, in compose_config
    self.stepper_wrapper.prepare_stepper()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 228, in prepare_stepper
    self.__make_stpd_file()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 318, in __make_stpd_file
    stepper.write(os)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 62, in write
    f.write(missile)

2023-04-29 21:20:03,900	Job number is not available yet
2023-04-29 21:20:03,903	Job number is not available yet
2023-04-29 21:20:03,927	File already exists: /var/loadtest/logs/2023-04-29_21-20-03.528313/phout_eWm5oH.log
2023-04-29 21:20:03,933	File already exists: /var/loadtest/logs/2023-04-29_21-20-03.528313/answ_J6HIFR.log
2023-04-29 21:20:03,939	File already exists: /var/loadtest/logs/2023-04-29_21-20-03.528313/phantom_stat_pvHhzl.log
2023-04-29 21:20:03,947	File not found to collect: validation_error.yaml
2023-04-29 21:20:03,952	File already exists: /var/loadtest/logs/2023-04-29_21-20-03.528313/phantom_fULmRU.log
2023-04-29 21:20:51,786	Interrupting
2023-04-29 21:20:56,480	File already exists: /var/loadtest/logs/2023-04-29_21-20-47.803000/phantom_Kr6omH.conf
2023-04-29 21:20:56,485	File already exists: /var/loadtest/logs/2023-04-29_21-20-47.803000/phantom_iWWBrn.log
2023-04-29 21:20:56,490	File already exists: /var/loadtest/logs/2023-04-29_21-20-47.803000/phout_bz0Xya.log
2023-04-29 21:20:56,494	File already exists: /var/loadtest/logs/2023-04-29_21-20-47.803000/answ_Sa8cNU.log
2023-04-29 21:20:56,499	File not found to collect: validation_error.yaml
2023-04-29 21:20:56,505	File already exists: /var/loadtest/logs/2023-04-29_21-20-47.803000/phantom_stat_6ic_RF.log
